### ISSUE TITLE
Allow non blocking once units

### ISSUE THREAD

**Issue by dani** [yankeguo/minit#13]
once units are started before daemon ones, and are blocking (daemon won't be started until once are terminated). In some cases, it'd be usefull to be able to run one command, without it blocking daemon starting in parallel.

A sample usecase : I run an elasticsearch node, and would like to run a script which configure index template. This script should only run once, so the kind: once is the most appropriate. Except that this script needs ES to be started. But as ES is a kind: daemon, it won't start until the configuration script terminates.

Something like
```yaml
kind: once
name: es-config
command: ["setup-index-template.sh"]
# Do not block, start daemons right away
blocking: false
```
