### ISSUE TITLE
Thanks ! (and a few enhancements ideas)

### ISSUE THREAD

**Issue by dani** [yankeguo/minit#9]
Hi.

First of all, many thanks for this tool. I've been looking for a flexible init / task manager for my containers,  and it took me a while before I found your minit project, which is almost exactly what I was looking for.

I only have a few ideas which would make it the perfect tool for me

- Support defining several units with env vars. For now, we can only define a single unit with

```
MINIT_MAIN=my_command
MINIT_MAIN_KIND=daemon
MINIT_MAIN_NAME=my-daemon
```
It'd be great to be able to define several units, like
```
MINIT_MAIN=lemonldap-ng
MINIT_MAIN_KIND=daemon
MINIT_MAIN_NAME="Lemonldap::NG uwsgi server"
MINIT_NGINX="nginx -c /etc/nginx/nginx.conf"
MINIT_NGINX_KIND=daemon
MINIT_CACHE=purgeCentralCache.sh
MINIT_CACHE_KIND=cron
MINIT_CACHE_CRON="* * * * *"
```

- Support using env var value for the cron scheduling, eg
```yaml
kind: cron
name: my cron task
cron: ${CRON_SCHEDULE}
immediate: true
```

- Support redering files from one dir to another. For now, the rendering of files can only be done inplace. It'd be great to have something like
```yaml
kind: render
name: template-renderer
from: /etc/templates/*.txt
to: /tmp/config/
```
The reason this would be useful is because I run most of my containers with a readonly rootfs (so the bundled templates can't be rendered in place). Of course, I could add a task which copy my readonly templates to /tmp/config and then render it inplace, but it'd be cleaner and easier to simply define source template and destination rendered files directly in the unit definition
